stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: meyasubako-gui
  ECR_URL: 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
  K8S_NODEPORT: 30556
  K8S_ECR_SECRET_NAME: ecr-credentials
  K8S_INGRESS_HOST: meyasubako.rnd-jtekt.local

image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

build:
  stage: build
  tags:
    - dind
  only:
    - master
  before_script:
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_PUBLIC_URL}
    - >
      aws ecr-public create-repository --region us-east-1 --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"

  script:
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  stage: deploy
  tags:
    - dind
  only:
    - master
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
