stages:
  - build
  - deploy

variables:
  APPLICATION_NAME: mendokusai-front
  ECR_URL: 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com
  CONTAINER_TAG: solid-${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE: ${ECR_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
  K8S_NODEPORT: 30556
  K8S_ECR_SECRET_NAME: ecr-credentials

image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

build:
  stage: build
  tags:
    - dind
  only:
    - solid
  before_script:
    # ECR login for pushing
    - >
      aws ecr get-login-password
      | docker login
      --username AWS
      --password-stdin
      ${ECR_URL}
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"
  script:
    # Build the container image
    - docker build -t ${CONTAINER_IMAGE_TAGGED} .
    # Push container images to registry
    - docker push ${CONTAINER_IMAGE_TAGGED}

deploy:
  stage: deploy
  tags:
    - dind
  before_script:
    # Create a secret with ECR credentials for K8s to pull
    # Here, we use apply to update it
    # https://stackoverflow.com/questions/47369351/kubectl-apply-vs-kubectl-create
    - >
      kubectl create secret docker-registry ${K8S_ECR_SECRET_NAME}
      --docker-server=${AWS_ECR_URL}
      --docker-username=AWS
      --docker-password $(aws ecr get-login-password)
      --dry-run=client -o yaml
      | kubectl apply -f -
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab

