apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${DOCKER_IMAGE}
        ports:
        - containerPort: 80
        env:
        - name: VUE_APP_MENDOKUSAI_API_URL
          value: 31040
        envFrom:
        - secretRef:
           name: environment-variables
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 80
    nodePort: 30555
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
